name: Vulnerability Audit

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Enter the domain or website URL for the audit'
        required: true
        default: 'http://example.com'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap nikto git unzip curl
          curl -LO https://github.com/drwetter/testssl.sh/archive/refs/heads/master.zip
          unzip master.zip
          chmod +x testssl.sh-master/testssl.sh

      - name: Run Nmap
        run: nmap -sV -oN nmap_results.txt ${{ github.event.inputs.url }}

      - name: Run Nikto
        run: nikto -h ${{ github.event.inputs.url }} -o nikto_results.txt

      - name: Run testssl.sh
        run: ./testssl.sh-master/testssl.sh --quiet ${{ github.event.inputs.url }} > testssl_results.txt

      - name: Check Security Headers
        run: |
          curl -s -D headers.txt -o /dev/null ${{ github.event.inputs.url }}

      - name: Generate Professional Markdown Report
        run: |
          REPORT="report.md"
          echo "# Vulnerability Audit Report for ${{ github.event.inputs.url }}" > $REPORT
          echo "" >> $REPORT
          echo "**Date:** $(date +'%Y-%m-%d')" >> $REPORT
          echo "**Audited By:** Whiteyeonline" >> $REPORT
          echo "" >> $REPORT
          echo "---" >> $REPORT
          echo "## How to Read This Report" >> $REPORT
          echo "" >> $REPORT
          echo "This report summarizes security checks performed on your website." >> $REPORT
          echo "- **Issues are listed with risk levels** (High, Medium, Low)." >> $REPORT
          echo "- Each finding has an explanation and a recommended fix." >> $REPORT
          echo "- Share this report with your developer or technical team to improve your site’s security." >> $REPORT
          echo "" >> $REPORT
          echo "---" >> $REPORT
          echo "## Summary" >> $REPORT
          echo "" >> $REPORT
          echo "| Issue Type             | Count | High Risk | Medium Risk | Low Risk |" >> $REPORT
          echo "|------------------------|-------|-----------|-------------|----------|" >> $REPORT
          echo "| Open Ports             | [##]  | [##]      | [##]        | [##]     |" >> $REPORT
          echo "| Web Server Issues      | [##]  | [##]      | [##]        | [##]     |" >> $REPORT
          echo "| SSL/TLS Problems       | [##]  | [##]      | [##]        | [##]     |" >> $REPORT
          echo "| Security Headers       | [##]  | [##]      | [##]        | [##]     |" >> $REPORT
          echo "" >> $REPORT
          echo "---" >> $REPORT
          echo "## Detailed Findings & Fixes" >> $REPORT
          echo "" >> $REPORT
          echo "### 1. Nmap Scan (Open Ports)" >> $REPORT
          echo "" >> $REPORT
          cat nmap_results.txt >> $REPORT
          echo "" >> $REPORT
          echo "- **Port 22 (SSH): Open**" >> $REPORT
          echo "  **Risk Level:** Medium" >> $REPORT
          echo "  **Why:** Attackers may try to log in." >> $REPORT
          echo "  **How to Fix:**" >> $REPORT
          echo "    - Disable SSH if not used" >> $REPORT
          echo "    - Restrict access to trusted IPs only" >> $REPORT
          echo "" >> $REPORT
          echo "- **Port 80 (HTTP): Open**" >> $REPORT
          echo "  **Risk Level:** Low" >> $REPORT
          echo "  **Why:** Standard for websites." >> $REPORT
          echo "  **How to Fix:**" >> $REPORT
          echo "    - Ensure your web server is up-to-date" >> $REPORT
          echo "" >> $REPORT
          echo "---" >> $REPORT
          echo "### 2. Nikto Scan (Web Server)" >> $REPORT
          echo "" >> $REPORT
          cat nikto_results.txt >> $REPORT
          echo "" >> $REPORT
          echo "- **Outdated Apache Server Version**" >> $REPORT
          echo "  **Risk Level:** Medium" >> $REPORT
          echo "  **Why:** Vulnerabilities in old versions" >> $REPORT
          echo "  **How to Fix:**" >> $REPORT
          echo "    - Update Apache using:" >> $REPORT
          echo "      \`sudo apt update && sudo apt upgrade apache2\`" >> $REPORT
          echo "" >> $REPORT
          echo "- **Directory Listing Enabled**" >> $REPORT
          echo "  **Risk Level:** Medium" >> $REPORT
          echo "  **Why:** Exposes files to attackers" >> $REPORT
          echo "  **How to Fix:**" >> $REPORT
          echo "    - Turn off directory listing in Apache config (\`Options -Indexes\`)" >> $REPORT
          echo "" >> $REPORT
          echo "---" >> $REPORT
          echo "### 3. testssl.sh (SSL/TLS)" >> $REPORT
          echo "" >> $REPORT
          cat testssl_results.txt >> $REPORT
          echo "" >> $REPORT
          echo "- **Weak Cipher Detected**" >> $REPORT
          echo "  **Risk Level:** High" >> $REPORT
          echo "  **Why:** Attackers can break weak encryption" >> $REPORT
          echo "  **How to Fix:**" >> $REPORT
          echo "    - Remove weak ciphers in your SSL config" >> $REPORT
          echo "    - Example for Apache:" >> $REPORT
          echo "      \`SSLCipherSuite HIGH:!aNULL:!MD5\`" >> $REPORT
          echo "" >> $REPORT
          echo "- **SSL Certificate Expired**" >> $REPORT
          echo "  **Risk Level:** High" >> $REPORT
          echo "  **Why:** Users see insecure warnings" >> $REPORT
          echo "  **How to Fix:**" >> $REPORT
          echo "    - Renew your SSL certificate" >> $REPORT
          echo "" >> $REPORT
          echo "---" >> $REPORT
          echo "### 4. Security Headers" >> $REPORT
          echo "" >> $REPORT
          cat headers.txt >> $REPORT
          echo "" >> $REPORT
          echo "- **Missing Content-Security-Policy**" >> $REPORT
          echo "  **Risk Level:** Medium" >> $REPORT
          echo "  **Why:** Increases risk of XSS attacks" >> $REPORT
          echo "  **How to Fix:**" >> $REPORT
          echo "    - Add this header in your server:" >> $REPORT
          echo "      \`Content-Security-Policy: default-src 'self';\`" >> $REPORT
          echo "" >> $REPORT
          echo "- **Missing X-Frame-Options**" >> $REPORT
          echo "  **Risk Level:** Medium" >> $REPORT
          echo "  **Why:** Prevents clickjacking" >> $REPORT
          echo "  **How to Fix:**" >> $REPORT
          echo "    - Add this header:" >> $REPORT
          echo "      \`X-Frame-Options: SAMEORIGIN\`" >> $REPORT
          echo "" >> $REPORT
          echo "---" >> $REPORT
          echo "## Risk Level Guide" >> $REPORT
          echo "" >> $REPORT
          echo "- **High:** Immediate attention needed. Potential for major security breach." >> $REPORT
          echo "- **Medium:** Should be fixed soon to improve security." >> $REPORT
          echo "- **Low:** Not urgent, but improves best practices." >> $REPORT
          echo "" >> $REPORT
          echo "**Thanks for using our services!**" >> $REPORT
          echo "" >> $REPORT
          echo "*This report was generated automatically. For best security, review and correct all High and Medium risk issues ASAP!*" >> $REPORT

      - name: Upload Professional Report
        uses: actions/upload-artifact@v2
        with:
          name: vulnerability-audit-report
          path: report.md
